#ifndef TDDMODULE_MAIN_H
#define TDDMODULE_MAIN_H

#include <linux/module.h>

// functions generated by module_ macros
ModuleInitFuncPtr __inittest(void);
ModuleExitFuncPtr __exittest(void);

int tddmodule_init(void);
void tddmodule_exit(void);

extern dev_t tddmodule_first_dev;

#endif

