#ifndef TDDMODULE_MAIN_H
#define TDDMODULE_MAIN_H

#include <linux/module.h>
#include "main_private.h"

// functions generated by module_ macros
ModuleInitFuncPtr __inittest(void);
ModuleExitFuncPtr __exittest(void);

int tddmodule_setup_cdev(void);

int tddmodule_init(void);
void tddmodule_exit(void);

int tddmodule_dev_open (struct inode *inode, struct file *filp);
int tddmodule_dev_release (struct inode *inode, struct file *filp);

extern dev_t tddmodule_first_dev;
extern tddmodule_dev_t tddmodule_dev; 
extern struct file_operations tddmodule_fops;

#endif

